//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EhImageZipViewer.Compression {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EhImageZipViewer.Compression.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Zip file use not support compression method. 的本地化字符串。
        /// </summary>
        internal static string CompressionMethodNotSupport {
            get {
                return ResourceManager.GetString("CompressionMethodNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End of Central Directory record could not be found. 的本地化字符串。
        /// </summary>
        internal static string EOCDNotFound {
            get {
                return ResourceManager.GetString("EOCDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressed Size cannot be held in an Int64. 的本地化字符串。
        /// </summary>
        internal static string FieldTooBigCompressedSize {
            get {
                return ResourceManager.GetString("FieldTooBigCompressedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local Header Offset cannot be held in an Int64. 的本地化字符串。
        /// </summary>
        internal static string FieldTooBigLocalHeaderOffset {
            get {
                return ResourceManager.GetString("FieldTooBigLocalHeaderOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of Entries cannot be held in an Int64. 的本地化字符串。
        /// </summary>
        internal static string FieldTooBigNumEntries {
            get {
                return ResourceManager.GetString("FieldTooBigNumEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset to Central Directory cannot be held in an Int64. 的本地化字符串。
        /// </summary>
        internal static string FieldTooBigOffsetToCD {
            get {
                return ResourceManager.GetString("FieldTooBigOffsetToCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset to Zip64 End Of Central Directory record cannot be held in an Int64. 的本地化字符串。
        /// </summary>
        internal static string FieldTooBigOffsetToZip64EOCD {
            get {
                return ResourceManager.GetString("FieldTooBigOffsetToZip64EOCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uncompressed Size cannot be held in an Int64. 的本地化字符串。
        /// </summary>
        internal static string FieldTooBigUncompressedSize {
            get {
                return ResourceManager.GetString("FieldTooBigUncompressedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incomplete message. 的本地化字符串。
        /// </summary>
        internal static string IncompleteMessage {
            get {
                return ResourceManager.GetString("IncompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid zip file or not support. 的本地化字符串。
        /// </summary>
        internal static string InvalidZipFileOrNotSupport {
            get {
                return ResourceManager.GetString("InvalidZipFileOrNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A local file is corrupt. 的本地化字符串。
        /// </summary>
        internal static string LocalFileCorrupt {
            get {
                return ResourceManager.GetString("LocalFileCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A local file header is corrupt. 的本地化字符串。
        /// </summary>
        internal static string LocalFileHeaderCorrupt {
            get {
                return ResourceManager.GetString("LocalFileHeaderCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Split or spanned archives are not supported. 的本地化字符串。
        /// </summary>
        internal static string SplitSpanned {
            get {
                return ResourceManager.GetString("SplitSpanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zip file corrupt: unexpected end of stream reached. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedEndOfStream {
            get {
                return ResourceManager.GetString("UnexpectedEndOfStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zip 64 End of Central Directory Record not where indicated. 的本地化字符串。
        /// </summary>
        internal static string Zip64EOCDNotWhereExpected {
            get {
                return ResourceManager.GetString("Zip64EOCDNotWhereExpected", resourceCulture);
            }
        }
    }
}
