//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EhImageZipViewer.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EhImageZipViewer.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        internal static string AppShell_HomeShellContent_Title {
            get {
                return ResourceManager.GetString("AppShell.HomeShellContent.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EH 图片查看器 的本地化字符串。
        /// </summary>
        internal static string AppShell_Title {
            get {
                return ResourceManager.GetString("AppShell.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎使用 EH 图片查看器 的本地化字符串。
        /// </summary>
        internal static string HomePage_Headline {
            get {
                return ResourceManager.GetString("HomePage.Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开含有图片的 zip 压缩包 的本地化字符串。
        /// </summary>
        internal static string HomePage_OpenButton_Hint {
            get {
                return ResourceManager.GetString("HomePage.OpenButton.Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string HomePage_OpenButton_Text {
            get {
                return ResourceManager.GetString("HomePage.OpenButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加文件夹（下次一定 的本地化字符串。
        /// </summary>
        internal static string HomePage_OpenDirButton_Text {
            get {
                return ResourceManager.GetString("HomePage.OpenDirButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击按钮打开含有图片的 zip 压缩包 的本地化字符串。
        /// </summary>
        internal static string HomePage_SubHeadline {
            get {
                return ResourceManager.GetString("HomePage.SubHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此应用可查看图片压缩包、浏览个人库。 的本地化字符串。
        /// </summary>
        internal static string HomePage_SubHeadline1 {
            get {
                return ResourceManager.GetString("HomePage.SubHeadline1", resourceCulture);
            }
        }
    }
}
